export const FETCH_USERS_START = "FETCH_USERS_START";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";
export const SET_USERS_SUMMARY = "SET_USERS_SUMMARY";
export const SELECT_USER = "SELECT_USER";